apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonLabels:
#   app.xgeeks.org/team: idp_geekathon
#   backstage.io/kubernetes-id: ai-starter-template

namespace: idpkathon-dev
# namespace: ai-starter-template-idp_geekathon-dev

resources:
- ../../base
- ingress.yaml

  # ATENTION name = image.name NOT name = spec.containers[0].name
images:
- name: ghcr.io/xgeeks-geekathon/ai-starter-template
  newTag: 6685a75
- name: ghcr.io/xgeeks-geekathon/ai-starter-template-datafeeder
  newTag: 6685a75
